Validate dart docs

diff --git a/.github/workflows/forui_build.yaml b/.github/workflows/forui_build.yaml
--- a/.github/workflows/forui_build.yaml
+++ b/.github/workflows/forui_build.yaml
@@ -31,6 +31,21 @@ jobs:
       - run: dart run build_runner build --delete-conflicting-outputs
       - run: flutter analyze
       - run: flutter test
+      - run: |
+          if output=$(dart doc --dry-run 2>&1); then
+              if echo "$output" | grep -q -i "warning:"; then
+                  echo "Documentation warnings found:"
+                  echo "$output" | grep -i "warning:"
+                  exit 1
+              else
+                  echo "No documentation warnings found!"
+                  exit 0
+              fi
+          else
+              echo "Error: dart doc command failed"
+              echo "$output"
+              exit 1
+          fi
 
   build-android:
     name: Build Android
